name: clockify
description: "Clockify project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter_intl:
  main_locale: de
  enabled: true

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  dots_indicator: ^2.1.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_architecture:
    git:
      url: https://x-token-auth:ATCTT3xFfGN0cf0Ifs1eXkb__0Aq5_EOQchDQ3W1foOSq5zPUdYr4fNAm5JARBJP4PQJqINuEUQLT2GUe2H-9EFEr-GFatA2Wbfqwr7Om0awQvNPQGA0EPDXEgkWyGeg62ROyeTwT_ZROuAJMQ-GatMy2MnhMgCjci5BBWyjRFvlIeg8GS3mVmM=3139756E@bitbucket.org/sbetroisdorf/flutter_architecture.git
      path: packages/flutter_architecture
  flutter_flavorizr: ^2.2.1
  flutter_form_builder: ^9.1.1
  flutter_hooks: ^0.20.4
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_system_proxy:
    git:
      url: https://github.com/BrowserStackCE/flutter_system_proxy.git
      ref: main
  flutter_widget_from_html: ^0.14.11
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.4.5
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  package_info_plus: ^4.2.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  shimmer: ^2.0.0
  svg_flutter: ^0.0.1
  dropdown_search: ^5.0.6
  sentry_dio: ^7.16.1
  sentry_flutter: ^7.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.2.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: ^8.0.3
  state_notifier_test: ^0.0.10
  theme_extender:
    git:
      url: https://github.com/Q-Agency/Theme-Extension-Generator.git
      path: packages/theme_extender


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  fonts:
    enabled: false